" ==============================================================================
" File: vimrc
" Author: goudunz1
" Email: goudunz1@outlook.com
" Inspired by chenxuan's vimrc
" https://github.com/chenxuan520/vim-fast
" ==============================================================================

let g:author = "goudunz1"
let g:email = "goudunz1@outlook.com"
let &l:foldmethod = "marker"
let g:default_browser = "firefox"
iabbrev <expr> @@n g:author
iabbrev <expr> @@e g:email

" ==============================================================================
" [vim options] {{{

let mapleader = ","             " use ',' as leader key
set nocompatible                " disable legacy mode(vi)
filetype plugin indent on       " enable plugin and indent based on file types
syntax on                       " enable built-in highlight
set t_Co=256                    " require terminal to use 256 colors
set noerrorbells                " turn off error bells
set visualbell t_vb=            " turn off visual beeping
set cmdheight=1                 " height of the cmd line
set showcmd                     " show input in the cmd line
set textwidth=0                 " disable auto <cr>
set ruler                       " show cursor position in status line
set laststatus=2                " show status line
set number                      " show line numbers
set relativenumber              " show relative line numbers
"set whichwrap+=h,l              " cursor key can cross rows
set matchpairs+=<:>             " % can now detect <>
set backspace=indent,eol,start  " delete special characters freely
set virtualedit=block           " virtual select inside a tab
set showtabline=2               " show tab menu
set splitbelow                  " split new window below
set splitright                  " split new vertical window right
set mouse=                      " enable mouse
set clipboard=unnamed           " host clipboard (require gvim)
set wildmenu                    " better command auto completion
set colorcolumn=80              " 80 characters warning line
set autoindent                  " auto indent according to the previous line
set cindent                     " turn on indent for c-like languages
set cinoptions=g0,:0,N-s,E-s,(0 " see :help cinoptions
set smartindent                 " smartly choose indent way
set expandtab                   " soft tabs instead of tabs
set shiftwidth=4                " use 4 spaces for auto shift
set tabstop=4                   " set width of tab to 4
set softtabstop=4               " use 4 spaces for a soft tab
set smarttab                    " smartly shift with tabs and spaces

set nowrap                      " disable line wrap if cursor too right
set sidescroll=1                " set number of columns to move if cursor too right
set sidescrolloff=1             " keep 1 visible column on the right
set scrolloff=1                 " keep 1 visible line at the bottom

set hlsearch                    " highlight the pattern
set incsearch                   " highlight the pattern when typing
set ignorecase                  " ignore search case
set smartcase                   " smartly ignore search case
"set wrapscan                    " searches wrap over EOF

set nobackup                    " disable backup file
set noswapfile                  " disable swap file
set autoread                    " auto load buffer if file changed
set confirm                     " raise a dialog when saving

" configurations for package matchit
packadd! matchit
packadd! termdebug

" }}}
" ==============================================================================

" ==============================================================================
" [plugin list] (managed by vim-plug) {{{

call plug#begin('~/.vim/plugged')

" onedark theme
Plug 'joshdick/onedark.vim'

" symbol list based on ctag/coc
Plug 'liuchengxu/vista.vim', {'on': 'Vista'}

" a modern fuzzy finder
Plug 'Yggdroot/LeaderF', {  'do': ':LeaderfInstallCExtension' }

" navigation sidebar tree
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }

" auto pair special characters
Plug 'jiangmiao/auto-pairs'

" auto code align with spaces
Plug 'godlygeek/tabular'

" modern auto completion plugin based on LSP servers
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" better command line prompt
Plug 'vim-airline/vim-airline'

" more icons (require nerd fonts)
Plug 'ryanoasis/vim-devicons'

" visualize vim movement
Plug 'easymotion/vim-easymotion'

" insert snippets quickly in vim (works together with coc-snippets)
Plug 'honza/vim-snippets'

" repeat find/till with f/t instead of ,/;
Plug 'rhysd/clever-f.vim'

call plug#end()

" }}}
" ==============================================================================

" ==============================================================================
" [user scripts] {{{

" toggle hidden characters
nnoremap <leader>l :let &l:list=!&l:list<cr>
xnoremap <leader>l :let &l:list=!&l:list<cr>

" toggle search pattern highlight
nnoremap <leader>h :noh<cr>
xnoremap <leader>h :noh<cr>

" eye friendly ctrl-o
nnoremap <c-o> <c-o>zz

" run marco in visual mode
xnoremap @ :normal! @

" substitute selected keyword (register s will be used!)
xnoremap <f2> "sy/\V\<<c-r>=@s<cr>\><cr><c-o>:%s/\V\<<c-r>=@s<cr>\>/

" use arrow keys for window commands {{{

" adjust window boundary
nnoremap <c-up> <c-w>+
xnoremap <c-up> <c-w>+
nnoremap <c-down> <c-w>-
xnoremap <c-down> <c-w>-
nnoremap <c-left> <c-w><
xnoremap <c-left> <c-w><
nnoremap <c-right> <c-w>>
xnoremap <c-right> <c-w>>

" change focused window
nnoremap <up> <c-w>k
xnoremap <up> <c-w>k
nnoremap <down> <c-w>j
xnoremap <down> <c-w>j
nnoremap <left> <c-w>h
xnoremap <left> <c-w>h
nnoremap <right> <c-w>l
xnoremap <right> <c-w>l

" }}}

" adjust selected area {{{

" move selected area upward/downward
xnoremap <c-k> :move '<-2<cr>gv
xnoremap <c-j> :move '>+1<cr>gv

" move selected area to window on the left/right
xnoremap <c-h> y<c-w>ho<c-[>vpgv
xnoremap <c-l> y<c-w>lo<c-[>vpgv

" }}}

" scroll in the other window (for reading or referrence){{{

" scroll pages
nnoremap \<c-u> <c-w>p<c-u><c-w>p
nnoremap \<c-d> <c-w>p<c-d><c-w>p
nnoremap \<c-f> <c-w>p<c-f><c-w>p
nnoremap \<c-b> <c-w>p<c-b><c-w>p
nnoremap \<c-y> <c-w>p<c-y><c-w>p
nnoremap \<c-e> <c-w>p<c-e><c-w>p

" adjust window
nnoremap \zz <c-w>zz<c-w>p
nnoremap \zt <c-w>zt<c-w>p
nnoremap \zb <c-w>pzb<c-w>p

" }}}

" window/tab multiply {{{

" open a new empty tab
nnoremap <leader><tab> :tabnew<cr>
xnoremap <leader><tab> :tabnew<cr>
nnoremap <leader><bs> :tabclose<cr>
xnoremap <leader><bs> :tabclose<cr>

" open a new empty window
nnoremap <leader>v :vert new<cr>
xnoremap <leader>v :vert new<cr>
nnoremap <leader>V :new<cr>
xnoremap <leader>V :new<cr>

" open up a terminal
nnoremap <leader>t :vert term<cr>
xnoremap <leader>t :vert term<cr>
nnoremap <leader>T :bo term ++rows=6<cr>
xnoremap <leader>T :bo term ++rows=6<cr>

" open up a terminal in a new tab
nnoremap <leader><leader>t :tabe<cr>:vert term ++curwin ++close<cr>
xnoremap <leader><leader>t :tabe<cr>:vert term ++curwin ++close<cr>

" open up a terminal in a new tab under directory of current file
nnoremap <leader><leader>T :tabe<cr>:call term_start("bash",{"cwd":"<c-r>=expand('%:p:h')<cr>","curwin":1,"term_finish":"close"})<cr>
xnoremap <leader><leader>T :tabe<cr>:call term_start("bash",{"cwd":"<c-r>=expand('%:p:h')<cr>","curwin":1,"term_finish":"close"})<cr>

" run async tasks with 'vert term'
command! -complete=shellcmd -nargs=+ AsyncRun exec "vert term ".<q-args>
cnoreab bang AsyncRun

" }}}

" buffer manipulation {{{

" reload/redraw buffer
nnoremap <leader>r :e<cr>
xnoremap <leader>r :e<cr>
nnoremap <leader>R :redraw!<cr>
xnoremap <leader>R :redraw!<cr>

func! s:change_buf(towards) abort
    if &bt != '' || &ft == 'netrw'
        echoerr "buffer". &bt. " cannot be changed"
        return
    endif
    if a:towards == 'n' | bn | else | bp | endif
	while &bt != '' || &ft == 'netrw'
        if a:towards == 'n' | bn | else | bp | endif
    endwhile
endfunc

" select previous buffer
nnoremap <c-p> :call<space><sid>change_buf('p')<cr>
xnoremap <c-p> :call<space><sid>change_buf('p')<cr>
nnoremap <leader>j :call<space><sid>change_buf('p')<cr>
xnoremap <leader>j :call<space><sid>change_buf('p')<cr>

" select next buffer
nnoremap <c-n> :call<space><sid>change_buf('n')<cr>
xnoremap <c-n> :call<space><sid>change_buf('n')<cr>
nnoremap <leader>k :call<space><sid>change_buf('n')<cr>
xnoremap <leader>k :call<space><sid>change_buf('n')<cr>

func! s:close_buf() abort
    if bufname() == '' || len(getbufinfo({'buflisted': 1})) == 0
        quit | return
    endif
    if &bt == '' | bdelete
    elseif &bt == 'quickfix' | cclose
    elseif &bt == 'loclist' | lclose
    else | close
    endif
endfunc

" leave current buffer
nnoremap <leader>q :call<space><sid>close_buf()<cr>
xnoremap <leader>q :call<space><sid>close_buf()<cr>

" save current buffer
nnoremap <leader>w :w<cr>
xnoremap <leader>w :w<cr>

" load file in new buffer
nnoremap <leader>e :edit<space><c-r>=getcwd()<cr>/
xnoremap <leader>e :edit<space><c-r>=getcwd()<cr>/
nnoremap <leader>E :edit<space>/
xnoremap <leader>E :edit<space>/

"}}}

" select until the next brace {{{

" locate nearest { below
nnoremap <leader>{ /{<cr>:noh<cr>va}
xnoremap <leader>{ <c-[>/{<cr>:noh<cr>va}

" locate nearest } above
nnoremap <leader>} ?}<cr>:noh<cr>va{
xnoremap <leader>} <c-[>?}<cr>:noh<cr>va{
" }}}

" super deletion {{{

" erase trailing spaces, example ggvGd<space>
nnoremap d<space> :'<,'>s/\s*$//<cr>:noh<cr><c-o>

" erase empty lines, example: ggvGd<cr>
nnoremap d<cr> :'<,'>/^\s*$/d<cr>:noh<cr>

" clear the current line
nnoremap dc d0d$

" re-enter the current line
nnoremap di d0d$i

" re-enter the current line (insert mode)
inoremap <c-d> <c-o>dd<c-o>O

" }}}

" yank and paste {{{

" yank a whole line
nnoremap yy v0$y

" yank from system clipboard
nnoremap <leader>y "+y
xnoremap <leader>y "+y

" paste to system clipboard
nnoremap <leader>p "+p
xnoremap <leader>p "+p
nnoremap <leader>P "+P
xnoremap <leader>P "+P

" }}}

" lazy indent/padding {{{

" quick indent in normal/visual mode 
nnoremap <tab> >>
xnoremap <tab> >gv
nnoremap <s-tab> <<
xnoremap <s-tab> <gv

" press <leader> then hold <space> to add more spaces
nnoremap <leader><space> i<space><c-[>:while getchar()==32<bar>undoj<bar>exec "normal!i<space>"<bar>redraw<bar>endwhile<cr>

" press <leader> then hold o/O to add empty lines on the previous/next line
nnoremap <leader>o :call append(line('.'),"")<cr>:while getchar()==111<bar>undoj<bar>call append(line('.'),"")<bar>redraw<bar>endwhile<cr>
nnoremap <leader>O :call append(line('.')-1,"")<cr>:while getchar()==79<bar>undoj<bar>call append(line('.')-1,"")<bar>redraw<bar>endwhile<cr>

" insert empty lines in normal mode
nnoremap \o :call append(line('.'),"")<cr>
nnoremap \O :call append(line('.')-1,"")<cr>

" }}}

" better command line {{{

" tcsh-style command line (bash compatible)
cnoremap <c-a> <home>
cnoremap <c-b> <left>
cnoremap <c-f> <right>

" command line key characters, you can modifiy these for better performance
let g:cmd_pairs={'(': ')', '[': ']', '{': '}', '<': '>', '"': '"', "'": "'", '`': '`'}

" auto complete command line key characters
func! s:cmd_auto_pair(ch)
    if has_key(g:cmd_pairs, a:ch)
        return a:ch. g:cmd_pairs[a:ch]. "\<left>"
    elseif a:ch == getcmdline()[getcmdpos() - 1]
        return "\<right>"
    else
        return a:ch
    endif
endfunc
cnoremap <expr> ( <sid>cmd_auto_pair('(')
cnoremap <expr> ) <sid>cmd_auto_pair(')')
cnoremap <expr> [ <sid>cmd_auto_pair('[')
cnoremap <expr> ] <sid>cmd_auto_pair(']')
cnoremap <expr> { <sid>cmd_auto_pair('{')
cnoremap <expr> } <sid>cmd_auto_pair('}')
cnoremap <expr> < <sid>cmd_auto_pair('<')
cnoremap <expr> > <sid>cmd_auto_pair('>')
cnoremap <expr> " <sid>cmd_auto_pair('"')
cnoremap <expr> ' <sid>cmd_auto_pair("'")
cnoremap <expr> ` <sid>cmd_auto_pair('`')

" auto delete verbose key characters
func! s:cmd_auto_bs()
    let cr = getcmdline()[getcmdpos() - 1]
    let cl = getcmdline()[getcmdpos() - 2]
    if has_key(g:cmd_pairs, cl) && (g:cmd_pairs[cl] == cr)
        return "\<right>\<bs>\<bs>"
    else
        return "\<bs>"
    endif
endfunc
cnoremap <expr> <bs> <sid>cmd_auto_bs()

" }}}

" buffer events {{{
augroup BufferEvents
    autocmd!
    " remember the last position when re-opening a buffer
    autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exec "normal! g'\"" | endif

    " set cursor line if and only if window on focus
    autocmd BufEnter,WinEnter * setlocal cursorline
    autocmd BufLeave,WinLeave * setlocal nocursorline
augroup end
" }}}

" jump to link at the cursor {{{
" use netrw's gx if present
if !exists("g:loaded_netrw")
    func! s:gx()
    	let m = matchstrpos(getline('.'), 'https*://\S[^][(){}]*')
    	while m[0] != '' && (m[1] > col('.') || m[2] < col('.'))
    		let m = matchstrpos(getline('.'), 'https*://\S[^][(){}]*', m[2])
    	endwhile
        if m[0] != ''
    	    let browser = get(g:, 'default_browser', 'firefox')
            let link = m[0]
            call job_start(browser. ' '. link)
        else
            echoerr 'cannot find link'
        endif
    endfunc
    nnoremap <nowait>gx :call<space><sid>gx()<cr>
endif

" }}}

" lazy io management {{{

" change pwd
cnoreab cd cd <c-r>=expand('%:p:h')<cr>

" remove current file
command! -nargs=0 -bang Remove call delete(expand('%')) | :bd | :bn
cnoreab rm Remove

" rename current file
command! -nargs=1 -bang -complete=file Rename let @s=expand('%') | file <args> | write! | call delete(@s)
cnoreab <expr>mv "Rename ".expand('%:p:h')

" make new directory
command! -nargs=1 -bang -complete=file Mkdir echo mkdir(<f-args>)
cnoreab <expr>md "Mkdir ".expand('%:p:h')

" remove directory
command! -nargs=1 -bang -complete=file Rmdir echo delete(<f-args>, "d")
cnoreab <expr>rd "Rmdir ".expand('%:p:h')

" force write
command! -nargs=0 -bang SudoWrite  w !sudo tee % >/dev/null
cnoreab w!! SudoWrite
nmap <leader>W :w!!<cr>
xmap <leader>W :w!!<cr>

" }}}

" quickfix {{{

" scroll between quickfix results
nnoremap <space>n :cnext<cr>
nnoremap <space>p :cprevious<cr>

" <space>+q to open quickfix window
nnoremap <expr> <space>q getwininfo()[winnr()-1]['quickfix']==1?":cclose\<cr>":":copen\<cr>"

" }}}

" vim diff {{{

" shortcuts to open up a vimdiff window
cab <expr>Diff "Diff ".expand('%:p:h')."/"
command! -nargs=1 -bang -complete=file Diff exec ":vert diffsplit ".<q-args>

" }}}

" termdebug {{{

" mappings for package termdebug
nnoremap <f5> :Termdebug<space>
nnoremap <f6> :Break<cr>
nnoremap <f7> :Over<cr>
nnoremap <f8> :Step<cr>

" vertical split termdebug windows
let g:termdebug_wide=1

" }}}

" }}}
" ==============================================================================

" ==============================================================================
" [plugin settings] {{{

" onedark.vim {{{

colorscheme onedark

" }}}

" vista.vim {{{

" enable vista icons
let g:vista#renderer#enable_icon=1

" default vista backend
let g:vista_default_executive='ctags'

" shortcut to inspect symbols
nnoremap <leader>u :Vista!!<cr>
nnoremap <leader>U :Vista!! coc<cr>

" delete buffer if vista is the only buffer remaining
augroup Vista
	autocmd!
	autocmd BufEnter * if (&ft == 'vista' || &ft == 'vista_markdown') && winnr('$') == 1 | bd | endif
augroup END

" }}}

" NERDTree {{{

" NERDTree sidebar width
let g:NERDTreeWinSize=28
    
" show all hidden files and folders
let g:NERDTreeShowHidden=1
    
" shortcut to open sidebar
nnoremap <leader>n :NERDTreeToggle<cr>
    
" delete buffer if NERDTree is the only buffer remaining
augroup NERDTree
    autocmd!
    autocmd BufEnter * if winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | bd | endif
augroup END

" }}}

" auto-pairs {{{

" disable some pre-defined mappings
let g:AutoPairsMapCh=0
let g:AutoPairsMapBS=0
let g:AutoPairsMapCR=0

" file specific pairs
augroup AutoPairs
    autocmd!
    autocmd FileType php let b:AutoPairs=AutoPairsDefine({'<?': '?>', '<?php': '?>'})
    autocmd FileType rust let b:AutoPairs=AutoPairsDefine({'\w\zs<': '>'})
    autocmd FileType html let b:AutoPairs=AutoPairsDefine({'<': '>', '<!--': '-->'})
augroup END

" }}}

" tabular {{{

nnoremap <leader>/" :Tabularize<space>/"\ze[^"]*$/l1c1l0
xnoremap <leader>/" :Tabularize<space>/"\ze[^"]*$/l1c1l0

nnoremap <leader>/# :Tabularize<space>/"\ze[^#]*$/l1c1l0
xnoremap <leader>/# :Tabularize<space>/"\ze[^#]*$/l1c1l0

nnoremap <leader>/ :Tabularize /
xnoremap <leader>/ :Tabularize /

" align <bar> in insert mode
func! s:align()
  let p = '^\s*|\s.*\s|\s*$'
  if exists(':Tabularize') && getline('.') =~# '^\s*|' && (getline(line('.')-1) =~# p || getline(line('.')+1) =~# p)
    let column = strlen(substitute(getline('.')[0:col('.')],'[^|]','','g'))
    let position = strlen(matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*'))
    Tabularize/|/l1
    normal! 0
    call search(repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.'))
  endif
endfunc

inoremap <bar> <bar><esc>:call <sid>align()<cr>a

" }}}

" vim-airline {{{

let g:airline_extensions = ['tabline', 'coc', 'branch']

" }}}

" vim-easymotion {{{

" ignore case when super moving
let g:EasyMotion_smartcase = 1

" trigger super move with \ + (vim default key)
map \ <plug>(easymotion-prefix)

" }}}

" LeaderF {{{

let g:Lf_WindowPosition = 'popup'

" }}}

" coc.nvim {{{

" always show notification column on the left
set signcolumn=yes

" use (shift-)tab to navigate
inoremap <silent><expr> <tab> coc#pum#visible() ? coc#pum#next(1) : "\<tab>"
inoremap <silent><expr> <s-tab> coc#pum#visible() ? coc#pum#prev(1) : "\<c-h>"

" use <cr> to confirm
inoremap <silent><expr> <cr> coc#pum#visible() ? coc#pum#confirm() : "\<cr>\<c-r>=coc#on_enter()\<cr>"

" }}}

" }}}
" ==============================================================================
